name: Update EC2 instance on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 instance
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Pull latest changes
        run: ssh ubuntu@ip-172-31-64-194 'cd /var/www/html/CC_Project_UE20CS351 && git pull'
      - name: Restart Nginx
        run: ssh ubuntu@ip-172-31-64-194 'sudo systemctl restart nginx'
